version: 3.0

stages:
   - build
   - deploy

build:
   stage: build
   job_type: image_build
   label: release-image
   build_dir: /
   dockerfile_path: /Dockerfile
   cache: true
   only:
      branches:
      - master
      tags:
      - .*

deploy:
  job_type: DCS_deploy
  stage: deploy
  app_name: Astral-Compose
  cluster_id: ""
  only:
    branches:
      - master
