version: 3.0

stages:
   - test
   - build
   - deploy
test:
   stage: test
   job_type: test
   label: develop
   image: ubuntu
   script:
      - echo non test now.
   only:
      branches:
      - master
      tags:
      - .*

build:
   stage: build
   job_type: image_build
   label: release-image
   build_dir: /
   dockerfile_path: /Dockerfile
   cache: true
   only:
      branches:
      - master
      tags:
      - .*

deploy:
  job_type: DCS_deploy
  stage: deploy
  app_name: Astral
  cluster_id: ""
  only:
    branches:
      - master
