version: 3.0

stages:
   - build

build:
   stage: build
   job_type: image_build
   label: release-image
   build_dir: /
   dockerfile_path: /Dockerfile
   cache: true
   only:
      branches:
      - master
      tags:
      - .*
