AstralCommandService:
  image: daocloud.io/scbizu/astral
  restart: always
  environment:
  - BOTKEY=${BOTKEY}
  command: astral service Command


AstralServerMessage:
  image: daocloud.io/scbizu/astral
  restart: always
  ports:
  - 8443:8443
  environment:
  - BOTKEY=${BOTKEY}
  - LISTENPORT=${LISTENPORT}
  command: astral service AstralServerMessage

AstralSC2EventInfo:
  image: daocloud.io/scbizu/astral
  restart: always
  environment:
  - BOTKEY=${BOTKEY}
  command: astral service SC2EventInfo
