AstralCommandService:
  image: daocloud.io/scbizu/astral:master
  restart: always
  ports:
  - 8443:8443
  environment:
  - BOTKEY={$BOTKEY}
  - LISTENPORT={$LISTENPORT}
  command:
  - /bin/sh
  - -c
  - "cd project/Astral \n./Astral service Command\n"

AstralServerMessage:
  image: daocloud.io/scbizu/astral:master
  restart: always
  ports:
  - 8443:8443
  environment:
  - BOTKEY={$BOTKEY}
  - LISTENPORT={$LISTENPORT}
  command:
  - /bin/sh
  - -c
  - "cd project/Astral \n./Astral service AstralServerMessage\n"

AstralSC2EventInfo:
  image: daocloud.io/scbizu/astral:master
  restart: always
  environment:
  - BOTKEY={$BOTKEY}
  - ASTRAL_DISCORD_CLIENT_ID={$DISCORD_CLIENT_ID}
  command:
  - /bin/sh
  - -c
  - "cd project/Astral \n./Astral service SC2EventInfo\n"
