# fly.toml app configuration file generated for astral-on-telegram on 2023-10-08T23:30:09+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "astral-on-telegram"
primary_region = "hkg"

[build]

[http_service]
  internal_port = 8443
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

