name: Astral

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ 'go1.17' ]
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Docker Image Metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build out Astral image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          # up to metadata action
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      # - name: Deploy Astral
      #   uses: wshihadeh/docker-deployment-action@v1
      #   run: |
      #     remote_docker_host: ${{ secrets.REMOTE_DOCKER_HOST }}
      #     remote_docker_port: ${{ secrets.REMOTE_DOCKER_PORT }}
      #     ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
      #     ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
      #     deployment_mode: docker-compose
      #     pull_images_first: true
